name: powercare_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
#dependencies:
#  flutter:
#    sdk: flutter
#
#  cupertino_icons: ^1.0.8
#
#  # SVG support
#  flutter_svg: ^2.0.10+1
#
#  # HTTP client
#  dio: ^5.9.0
#
#  # Image Picker
#  image_picker: ^1.1.2
#
#  # File Picker
#  file_picker: ^8.0.3
#
#  # Audio Recording
#  record: ^6.2.0
#
#  # Audio Player (for playing back recordings if needed)
#  audioplayers: ^6.6.0
#
#  # JSON parsing
#  json_annotation: ^4.9.0
#
#  # State management
#  flutter_riverpod: ^2.3.3
#
#  # Real-time socket
#  socket_io_client: ^2.0.0
#
#  # Local storage
#  shared_preferences: ^2.2.1
#
#  #for secure storage like token
#  flutter_secure_storage: ^10.0.0
##  firebase_core: ^4.9.0
##  firebase_messaging: ^16.1.0
#  flutter_local_notifications: ^21.0.0
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#
#  flutter_lints: ^6.0.0
#  build_runner: ^2.4.8
#  json_serializable: ^6.11.4
#  flutter_launcher_icons: ^0.14.3
#  http: ^1.2.1
#  device_info_plus: ^11.1.0
#  local_auth: ^2.3.0
#  firebase_core: ^4.7.0
#  firebase_messaging: ^16.1.0
#  flutter_local_notifications: ^21.0.0
#  url_launcher: ^6.2.5
#  webview_flutter: ^4.10.0
#  package_info_plus: ^8.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  dio: ^5.9.0
  image_picker: ^1.1.2
#  file_picker: ^12.0.0-beta.7
#  record: ^7.1.0
#  audioplayers: ^6.6.0
#  json_annotation: ^4.9.0
#  flutter_riverpod: ^2.3.3
  socket_io_client: ^3.1.6
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^10.0.0
  flutter_local_notifications: ^22.0.1

  # Move these here
  firebase_core: ^4.7.0
  firebase_messaging: ^16.1.0
  device_info_plus: ^13.1.0
  local_auth: ^3.0.1
  url_launcher: ^6.2.5
  webview_flutter: ^4.10.0
  package_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.11.4
  flutter_launcher_icons: ^0.14.3
  http: ^1.2.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/prod/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/prod/logo.png"
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  flavors:
    dev:
      android: true
      ios: true
      image_path: "assets/icons/dev/logo.png"
      adaptive_icon_background: "#FFFFFF"
      background_color_ios: "#FFFFFF"
      adaptive_icon_foreground: "assets/icons/dev/logo.png"
    prod:
      android: true
      ios: true
      image_path: "assets/icons/prod/logo.png"
      adaptive_icon_background: "#FFFFFF"
      background_color_ios: "#FFFFFF"
      adaptive_icon_foreground: "assets/icons/prod/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700

